title: Don-gik blog
description: notes, codes, and my life
url: https://don-gik.github.io
baseurl: ""
timezone: Asia/Seoul
minimal_mistakes_skin: "default"
logo: /assets/images/site-logo.png
author:
  name: "don-gik"
  avatar: /assets/images/me.jpg
  bio: "programming • music"
defaults:
  - scope: {path: "" , type: "posts"}
    values: {layout: "single", author_profile: true}
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
  sass_dir: assets/css

paginate: 10
paginate_path: "/page:num"  

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"


search: true
search_full_content: true
search_provider: lunr

rouge:
  linenos: table