title: Don-gik blog
description: notes, codes, and my life
url: https://don-gik.github.io
baseurl: ""
timezone: Asia/Seoul
# Social + metadata
github_username: don-gik
# Using a custom in-repo theme (no external Jekyll theme)
theme: null
logo: /assets/images/site-logo.png
author:
  name: "don-gik"
  avatar: /assets/images/me.jpg
  bio: "Hello I'm dongik. This is my blog."
  github: don-gik
  email: don-gik@users.noreply.github.com
  email_follow_url: https://buttondown.email/don-gik

newsletter_action: "https://buttondown.email/api/emails/embed-subscribe/don-gik"
newsletter_placeholder: "you@example.com"
newsletter_cta: "Follow"
newsletter_url: "https://buttondown.email/don-gik"


defaults:
  - scope: {path: "" , type: "posts"}
    values: {layout: "single", author_profile: true}
  - scope: {path: "", type: "pages"}
    values: {author_profile: true}
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
  sass_dir: assets/css
  sass_compiler: sassc

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    # theme: 'monokai.sublime' # This is not a valid option here, it's a custom css

excerpt_separator: "<!--more-->"


search: true
search_full_content: true
search_provider: lunr

rouge:
  linenos: table
