title: Don-gik blog
description: notes, codes, and my life
url: https://don-gik.github.io
baseurl: ""
timezone: Asia/Seoul
minimal_mistakes_skin: "dark"
logo: /assets/images/site-logo.png
author:
  name: "don-gik"
  avatar: /assets/images/me.jpg
  bio: "Hello I'm dongik. This is my blog."


defaults:
  - scope: {path: "" , type: "posts"}
    values: {layout: "single", author_profile: true}
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginator-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
  sass_dir: assets/css

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    # theme: 'monokai.sublime' # This is not a valid option here, it's a custom css

excerpt_separator: "<!--more-->"


search: true
search_full_content: true
search_provider: lunr

rouge:
  linenos: table
