source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins do
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "webrick", "~> 1.9"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "jekyll-paginator-v2"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "rouge", "~> 4.2"
gem "jekyll-sass-converter", "~> 2.2"
gem "sass-embedded", "~> 1.80"
end